import lodstorage

from lodstorage.sparql import SPARQL

#print("hello world\n")

endpoint="https://query.wikidata.org/sparql"
wd=SPARQL(endpoint)
queryString="""# truly tabular naive query for 
# Q47258130:scientific conference series
# generated by trulytabular.py version 0.4.7 on 2022-11-03T11:48:07.334177
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?scientific_conference_seriesItem ?scientific_conference_series
  ?official_website
  ?title
WHERE {
  # instanceof Q47258130:scientific conference series
  ?scientific_conference_seriesItem wdt:P31 wd:Q47258130.
  # label
  ?scientific_conference_seriesItem rdfs:label ?scientific_conference_series.  
  FILTER (LANG(?scientific_conference_series) = "en").
  # official website (P856)
  OPTIONAL { 
    ?scientific_conference_seriesItem wdt:P856 ?official_website. 
  }
  # title (P1476)
  OPTIONAL { 
    ?scientific_conference_seriesItem wdt:P1476 ?title. 
  }
}
LIMIT 1000
"""
#results=wd.query(queryString)[0:1000]
results=wd.query(queryString)

for e in results:
  if e.get('official_website'):
    print(e.get('scientific_conference_series'), e.get('official_website'))
    print(str(e.get('official_website')).split('\'')[1])